---
- hosts: controller
  tasks:
  - shell: echo "162.105.85.181  controller1" >> /etc/hosts
  - shell: echo "162.105.85.173  controller2" >> /etc/hosts
  - shell: echo "162.105.85.195  controller3" >> /etc/hosts
